apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maanantai
  description: ping-demo
  annotations:
    backstage.io/kubernetes-id: maanantai
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: RedHatNordicsSA/maanantai
spec:
  type: api
  system: 
  lifecycle: production
  owner: cool-lab
